
[DepthStencilStateDX11]
DepthEnable = true
DepthFunc = D3D11_COMPARISON_GREATER_EQUAL

[RasterizerStateDX11]
CullMode = D3D11_CULL_BACK

[SamplerDX11_1]

[SamplerDX11_2]
ComparisonFunc = D3D11_COMPARISON_GREATER_EQUAL
Filter = D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT
